# docker-compose.yml
version: "3.3"
services:
  api:
    image: alivx:enc_api
    ports:
      - "1992:1992"
    network_mode: host
    depends_on:
      - redis

  redis:
    image: alivx:enc_redis
    network_mode: host
    ports:
      - "6379:6379"
    volumes:
      - enc_redis:/var/lib/redis

volumes:
  enc_redis: